### ISSUE TITLE
Error on Mac

### ISSUE THREAD

**Issue by yanivtal** [m-ou-se/teck-programmer#2]
Thanks for making this.

```
Found device in normal mode on bus 20, device 1.
Switching to program mode.
Error: LIBUSB_ERROR_ACCESS
```

**Comment by m-ou-se** [comment]
I forgot to re-publish the package after the last update. Does it work if you re-install/update and try again?

**Comment by yanivtal** [comment]
Weee it works. Thanks you rock!
