### ISSUE TITLE
Can't program more than once

### ISSUE THREAD

**Issue by yanivtal** [m-ou-se/teck-programmer#3]
I was able to successfully program on my Mac once but now every time I try to go program I get this:

```
Found device in normal mode on bus 20, device 13.
Switching to program mode.
Rescanning for devices in one second.
Error: No devices found.
```

**Comment by m-ou-se** [comment]
After switching the keyboard to program mode, the tool waits a second before continuing. It might happen sometimes that it takes longer than a second for the computer to reconnect to the keyboard after it switches. In that case, it should work fine if you just run the command again. (It'll detect that the keyboard is already in program mode, and skips directly to programming.)

Do you keep having this problem? Does it work if you just run the tool again?

**Comment by yanivtal** [comment]
It failed like 4 times in a row. I tried it on an iMac, changed the rescan wait time to 3 seconds and it worked. Not sure if it's cus it was a different computer or cus of the 3 seconds. Might want to bump the time up anyway, but feel free to close. Thanks!

**Comment by justjacksonn** [comment]
not sure if this would help but could you run a linux vm or maybe even try docker with an ubuntu image with and see if it would work that way

**Comment by m-ou-se** [comment]
It should work fine now on Mac. There's also a better program for Mac: https://github.com/m-ou-se/tek/releases
