### ISSUE TITLE
LIBUSB_ERROR_ACCESS on Linux

### ISSUE THREAD

**Issue by seanh** [m-ou-se/teck-programmer#6]
Hi, just installed teck-programmer via npm today. I have set dip switch 5 to the programmable position. I'm getting this error:

``` bash
$ npm install -g teck-programmer
...
$ teck-firmware-upgrade ../TrulyErgonomic_v4_00\ \(1\).hex
Found device in normal mode on bus 1, device 4.
Switching to program mode.
Error: LIBUSB_ERROR_ACCESS
$ npm info -g teck-programmer | ag 'version:'
  version: '1.1.1',
$ 
```

Tried all three of my laptop's USB ports, same error. The keyboard is a TEK-S-229-US. ThinkPad X230 laptop. Ubuntu 16.04.

Thanks!

**Comment by m-ou-se** [comment]
It looks like the user the program runs as doesn't have permission to talk to the usb device directly. Did you copy [40-teck.rules](https://github.com/m-ou-se/teck-programmer/blob/master/40-teck.rules) into `/etc/udev/rules.d`? (Afterwards run `udevadm trigger` or just unplug and replug the keyboard.)

**Comment by seanh** [comment]
Oh, sorry, I missed that line in the readme. It works! Thanks
